### ISSUE TITLE
Missing Specs Audit

### ISSUE THREAD

**Issue by adonesky1** [MetaMask/api-specs#124]
**Missing MetaMask Methods**
- [x] `eth_requestAccounts` [https://eips.ethereum.org/EIPS/eip-1102] (issue: https://github.com/MetaMask/api-specs/issues/101)

**Missing Client methods**
- [ ] `eth_getUncleByBlockHashAndIndex`, `eth_getUncleByBlockNumberAndIndex,` (not in `ethereum/execution-apis` but supported by major infra nodes [including infura](https://docs.infura.io/infura/networks/ethereum/json-rpc-methods/eth_getunclebyblocknumberandindex))
- [ ] `eth_protocolVersion` ([removed from `ethereum/execution-apis`](https://github.com/ethereum/execution-apis/pull/264/files)? but [infura supports](https://docs.infura.io/infura/networks/ethereum/json-rpc-methods/eth_protocolversion))
- [x] `eth_subscribe` / `eth_unsubscribe` [https://eips.ethereum.org/EIPS/eip-758] (issue: https://github.com/MetaMask/api-specs/issues/89)
- [ ] `eth_sign` [we've semi deprecated so maybe not?]

**WIP**
- eth_signTypedData [https://github.com/MetaMask/api-specs/pull/123]

**MetaMask specific methods that are complete:**
- wallet_addEthereumChain
- wallet_switchEthereumChain
- wallet_requestPermissions
- wallet_getPermissions
- wallet_registerOnboarding
- wallet_watchAsset
- eth_decrypt
- eth_getEncryptionPublicKey
- eth_accounts
- personal_sign

**Comment by alexandratran** [comment]
I don't think `eth_sign` needs to be documented (we note it's deprecation [here](https://metamask.github.io/mm-docs-v2/staging/wallet/how-to/sign-data) and [here](https://metamask.github.io/mm-docs-v2/staging/wallet/concepts/signing-methods)), and it looks like we also need to document [`wallet_scanQRCode`](https://metamask.github.io/mm-docs-v2/staging/wallet/reference/rpc-api#wallet_scanqrcode) for mobile devs.
